### PR TITLE
On shutdown try to drain connections for 30s and close them

### LINKED ISSUE #960: systemctl restart and systemctl stop seems to hang on ubuntu 24.04 if websockets are in use
## Expected Behavior

Executing `sudo systemctl restart forwarder` should stop the deamon and disconnect any clients immediately and restart even if websocket connections are active.

## Actual Behavior

Executing it will hang as long as all websocket clients are active.  We get the same behavior with or `sudo systemctl stop forwarder`.
After all websocket clients are closed, forwarder restarts/stops.

Note: the vast majority of sites using websockets have auto-reconnect handlers in place because websocket streams are so unreliable.

## Steps to Reproduce the Problem

  1. Run forwarder on a proxy server
  2. Setup proxy in web browser to use the proxy server
  3. Connect to a website using websockets
  4. Try to execute `sudo systemctl restart forwarder` (or `sudo systemctl stop forwarder`) on the proxy server
  5. Watch nothing happen :-)

## Specifications

  - Version: v1.3.2
  - Platform: Ubuntu 24.04
  - Subsystem:

### PR DESCRIPTION
**Pull request by mmatczuk**
Shutdown tries to drain connections for 30s or until terminate signal is received, then they are closed. 

Fixes #960

### CODE REVIEW

File: http_proxy.go [hunk 1]
```diff
@@ -628,22 +649,11 @@ func (hp *HTTPProxy) Addr() (addrs []string, ok bool) {
...
-
-	// Shutdown the proxy to stop serving requests.
-	if e := hp.proxy.Shutdown(context.Background()); e != nil {
-		err = multierr.Append(err, e)
-	}
-
-	if tr, ok := hp.transport.(*http.Transport); ok {
-		tr.CloseIdleConnections()
-	}
-
```
Comment (Choraden) [inline http_proxy.go:634]: So now there is a `Close` that closes listeners, but user still needs to cancel ctx. 
Let's hide `Close` method and use in it Run. This way all workflow will be in `Run`.

Comment (mmatczuk) [reply http_proxy.go]: After implementing it I think the Close method gives users possibility for cleanup without relying on GC. It's actually kind of sad that the variable is not freed when it goes out of scope i.e. test function ends but that's how it is.

I'm reverting the last commit.

Comment (Choraden) [reply http_proxy.go]: ok
