### PR TITLE
martian(mitm): fix connect error response propagation

### LINKED ISSUE #510: mitm: handle upstream proxy error responses for CONNECT requests
When HTTP client fails HTTPS CONNECT request, it does not return the original response, but an error.

### PR DESCRIPTION
**Pull request by mmatczuk**
Fixes #510

### CODE REVIEW

File: internal/martian/proxy_connect.go [hunk 1]
```diff
@@ -201,3 +202,34 @@ func shouldTerminateTLS(req *http.Request) bool {
...
+	return e.res
+}
+
+func OnProxyConnectResponse(_ context.Context, _ *url.URL, req *http.Request, connectRes *http.Response) error {
+	if connectRes.StatusCode/100 == 2 {
+		return nil
+	}
+
+	// Body cannot be read from the CONNECT response due to use of closed network connection.
+	res := proxyutil.NewResponse(connectRes.StatusCode, http.NoBody, req)
```
Comment (Choraden) [inline internal/martian/proxy_connect.go:224]: How about calling body.Close() as a best effort approach?

Comment (Choraden) [reply internal/martian/proxy_connect.go:224]: N/m. I can see the conn is closed when returned error is not nil.

**Review by Choraden — APPROVED** [review]
LGTM
