### PR TITLE
Fix reading api-address from config file in container

### LINKED ISSUE #873: docker: use unix socket for health checks
Currently health checks add additional assumptions that prevent api-address config option working in docker container if passed in a config file.

Expose api server, regardless of --api-address flag, over unix socket if running in a container and use that for health checks.

### PR DESCRIPTION
**Pull request by mmatczuk**
This patchset implements checking readiness over a Unix socket.
Unnecessary API servers in e2e tests are removed.
The ready command implementation is extended and improved for better reuse.   

Fixes #873

### CODE REVIEW

File: Containerfile [hunk 1]
```diff
@@ -2,6 +2,8 @@ ARG BASE_IMAGE=gcr.io/distroless/static:nonroot
 
 FROM ${BASE_IMAGE}
 
+ENV PLATFORM=container
```
Comment (Choraden) [inline Containerfile:5]: How about `FORWARDER_PLATFORM`? Something to make it difficult to overwrite.

File: utils/httpx/httpx.go [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+			return ctx
+		},
+	}
+
+	go func() {
+		<-ctx.Done()
+		s.Close()
+	}()
+
+	return s.Serve(l)
```
Comment (Choraden) [inline utils/httpx/httpx.go:43]: It returns an error on server close 
```
^C2024/08/01 08:12:27.518332 [ERROR] fatal error exiting: http: Server closed
exit status 1
```

File: utils/httpx/httpx.go [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+import (
+	"context"
+	"fmt"
+	"net"
+	"net/http"
+	"os"
+	"time"
+)
+
+func ServeUnixSocket(ctx context.Context, h http.Handler, socketPath string) error {
```
Comment (Choraden) [inline utils/httpx/httpx.go:18]: May we add some logging here?

File: Containerfile (hunk 1 above)
Comment (mmatczuk) [reply Containerfile:5]: I don't know the `FORWARDER_PLATFORM` does not make much sense to me. 

We have two situations:
* The `PLATFORM` env var get overwritten when running container - for that we could log warning in the readiness check.
* Our container behavior kicking in in another setting due to presence of the env var - here I think we are good since we must match both key and value (container)  

Let me add some more logging instead.

File: utils/httpx/httpx.go (hunk 3 above)
Comment (mmatczuk) [reply utils/httpx/httpx.go:18]: Any logging should go in handler.

File: Containerfile (hunk 1 above)
Comment (mmatczuk) [reply Containerfile:5]: I considered adding sth like this

```
	if p := os.Getenv("PLATFORM"); p != "" {
		if  p == "container" {
			c.apiAddr = "unix:" + cfg.APIUnixSocket
		} else {
			fmt.Fprintf(os.Stderr, "unexpected PLATFORM environment variable: %q\n", p)
		}
	}
```

But I guess it's not really useful.

Comment (Choraden) [reply Containerfile:5]: Ugly^

Comment (Choraden) [reply Containerfile:5]: Maybe I'm exaggerating, why would somebody add PLATFORM variable to forwarder container.

**Review by Choraden — APPROVED** [review]
LGTM
